version: '3.3'  # Change this to a supported version

services:
  # web:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"

  #   environment:
  #     - PYTHONUNBUFFERED=1
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    networks:
      - dev
  frontend: 
    build:
      context: ./front  # Путь к директории с Dockerfile для Vue.js
    networks:
      - dev

networks:
  dev: