version: '3.3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - /root/hack_09.11:/etc/nginx/ssl # Монтируем директорию с сертификатами
      - ./:/var/www/html
    networks:
      - dev
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front  # Path to directory with Dockerfile for Vue.js
    networks:
      - dev

networks:
  dev: